const Y = 128;

export const SCAPE_PRESETS = {
  iwagumi: {
    name: 'Iwagumi',
    blurb: 'Stone hierarchy with sweeping background stems, restrained foreground epiphytes, and clean negative space.',
    assets: [
      { id: 'iwa_oyaishi', key: 'stone_seiryu_lg', x: 132, y: Y, scale: 1.24, rotation: -12, flip: false, depth: 'mid' },
      { id: 'iwa_fukuishi_l', key: 'stone_seiryu_lg', x: 84, y: Y + 1, scale: 0.94, rotation: 8, flip: true, depth: 'mid' },
      { id: 'iwa_fukuishi_r', key: 'stone_dragon', x: 176, y: Y + 1, scale: 0.86, rotation: -9, flip: false, depth: 'mid' },
      { id: 'iwa_suteishi1', key: 'stone_seiryu_sm', x: 58, y: Y + 2, scale: 0.70, rotation: 6, flip: false, depth: 'front' },
      { id: 'iwa_suteishi2', key: 'stone_seiryu_sm', x: 204, y: Y + 2, scale: 0.66, rotation: -4, flip: true, depth: 'front' },
      { id: 'iwa_suteishi3', key: 'stone_lava', x: 154, y: Y + 2, scale: 0.62, rotation: 3, flip: true, depth: 'front' },
      { id: 'iwa_rot_l1', key: 'rotala_full', x: 24, y: Y, scale: 0.94, rotation: 0, flip: false, depth: 'back' },
      { id: 'iwa_rot_l2', key: 'rotala_mid', x: 40, y: Y, scale: 0.90, rotation: 0, flip: true, depth: 'back' },
      { id: 'iwa_rot_mid', key: 'rotala_small', x: 152, y: Y, scale: 0.86, rotation: 0, flip: false, depth: 'back' },
      { id: 'iwa_rot_r1', key: 'rotala_full', x: 222, y: Y, scale: 1.0, rotation: 0, flip: true, depth: 'back' },
      { id: 'iwa_rot_r2', key: 'rotala_mid', x: 240, y: Y, scale: 0.94, rotation: 0, flip: false, depth: 'back' },
      { id: 'iwa_rot_r3', key: 'rotala_small', x: 258, y: Y, scale: 0.88, rotation: 0, flip: true, depth: 'back' },
      { id: 'iwa_val_l', key: 'vallisneria', x: 14, y: Y, scale: 0.64, rotation: 0, flip: false, depth: 'back' },
      { id: 'iwa_val_r', key: 'vallisneria', x: 272, y: Y, scale: 0.70, rotation: 0, flip: true, depth: 'back' },
      { id: 'iwa_fern_c', key: 'java_fern', x: 120, y: Y + 1, scale: 0.72, rotation: -1, flip: false, depth: 'front' },
      { id: 'iwa_fern_r', key: 'java_fern', x: 164, y: Y + 1, scale: 0.66, rotation: 2, flip: true, depth: 'front' },
      { id: 'iwa_anubias_l', key: 'anubias', x: 88, y: Y + 1, scale: 0.74, rotation: -2, flip: false, depth: 'front' },
      { id: 'iwa_anubias_r', key: 'anubias', x: 186, y: Y + 1, scale: 0.70, rotation: 2, flip: true, depth: 'front' },
      { id: 'iwa_moss', key: 'moss', x: 146, y: Y + 1, scale: 0.62, rotation: 0, flip: false, depth: 'front' },
      { id: 'iwa_float_l', key: 'floating_salvinia', x: 52, y: 16, scale: 0.88, rotation: 0, flip: false, depth: 'front' },
      { id: 'iwa_float_mid', key: 'floating_redroot', x: 138, y: 16, scale: 0.84, rotation: 0, flip: true, depth: 'front' },
      { id: 'iwa_float_r', key: 'floating_salvinia', x: 216, y: 16, scale: 0.86, rotation: 0, flip: true, depth: 'front' },
    ],
  },
  nature: {
    name: 'Nature Aquarium',
    blurb: 'Dense nature style with intertwined wood, colorful stems, floaters, and full-height plant mass.',
    assets: [
      { id: 'nat_stone_l', key: 'stone_seiryu_sm', x: 30, y: Y + 2, scale: 0.78, rotation: -8, flip: true, depth: 'front' },
      { id: 'nat_stone_core', key: 'stone_seiryu_lg', x: 88, y: Y, scale: 1.02, rotation: -5, flip: false, depth: 'mid' },
      { id: 'nat_stone_bridge', key: 'stone_dragon', x: 122, y: Y + 1, scale: 0.76, rotation: -6, flip: false, depth: 'mid' },
      { id: 'nat_wood_main', key: 'wood_manzanita', x: 146, y: Y + 2, scale: 0.72, rotation: -7, flip: false, depth: 'mid' },
      { id: 'nat_wood_side', key: 'wood_redmoor', x: 204, y: Y + 2, scale: 0.66, rotation: -10, flip: false, depth: 'mid' },
      { id: 'nat_wood_fill', key: 'wood_spider', x: 236, y: Y + 2, scale: 0.52, rotation: -9, flip: true, depth: 'mid' },
      { id: 'nat_rotala_l1', key: 'rotala_full', x: 22, y: Y, scale: 0.90, rotation: 0, flip: false, depth: 'back' },
      { id: 'nat_rotala_l2', key: 'rotala_mid', x: 40, y: Y, scale: 0.88, rotation: 0, flip: true, depth: 'back' },
      { id: 'nat_rotala_c1', key: 'rotala_full', x: 164, y: Y, scale: 1.04, rotation: 0, flip: false, depth: 'back' },
      { id: 'nat_rotala_c2', key: 'rotala_mid', x: 182, y: Y, scale: 1.00, rotation: 0, flip: true, depth: 'back' },
      { id: 'nat_rotala_r1', key: 'rotala_full', x: 206, y: Y, scale: 1.00, rotation: 0, flip: true, depth: 'back' },
      { id: 'nat_rotala_r2', key: 'rotala_mid', x: 224, y: Y, scale: 0.94, rotation: 0, flip: true, depth: 'back' },
      { id: 'nat_crypt_left', key: 'crypt', x: 62, y: Y, scale: 0.72, rotation: 0, flip: false, depth: 'back' },
      { id: 'nat_crypt_mid', key: 'crypt', x: 198, y: Y, scale: 0.70, rotation: 0, flip: true, depth: 'back' },
      { id: 'nat_lotus', key: 'buce', x: 152, y: Y + 1, scale: 0.72, rotation: -2, flip: false, depth: 'mid' },
      { id: 'nat_val_r1', key: 'vallisneria', x: 246, y: Y, scale: 0.68, rotation: 0, flip: false, depth: 'back' },
      { id: 'nat_val_r2', key: 'vallisneria', x: 266, y: Y, scale: 0.64, rotation: 0, flip: true, depth: 'back' },
      { id: 'nat_fern_lg', key: 'java_fern', x: 114, y: Y + 1, scale: 0.78, rotation: -2, flip: false, depth: 'front' },
      { id: 'nat_fern_mid', key: 'java_fern', x: 170, y: Y + 1, scale: 0.74, rotation: 2, flip: true, depth: 'front' },
      { id: 'nat_anubias_l', key: 'anubias', x: 70, y: Y + 1, scale: 0.76, rotation: 0, flip: false, depth: 'front' },
      { id: 'nat_anubias_r', key: 'anubias', x: 98, y: Y + 1, scale: 0.72, rotation: -1, flip: true, depth: 'front' },
      { id: 'nat_moss_fill', key: 'moss', x: 146, y: Y + 1, scale: 0.62, rotation: 0, flip: false, depth: 'front' },
      { id: 'nat_float_l', key: 'floating_redroot', x: 76, y: 16, scale: 0.86, rotation: 0, flip: true, depth: 'front' },
      { id: 'nat_float_c', key: 'floating_salvinia', x: 140, y: 16, scale: 0.92, rotation: 0, flip: false, depth: 'front' },
      { id: 'nat_float_r', key: 'floating_redroot', x: 214, y: 16, scale: 0.88, rotation: 0, flip: false, depth: 'front' },
    ],
  },
  hd2d_slice: {
    name: 'HD-2D Slice',
    blurb: 'Vertical-slice composition for atlas-quality review: realistic fauna proportions, clear silhouettes, subtle depth.',
    assets: [
      { id: 'h2_rock_1', key: 'stone_seiryu_lg', x: 92, y: Y, scale: 1.0, rotation: -5, flip: false, depth: 'mid' },
      { id: 'h2_rock_2', key: 'stone_pagoda', x: 128, y: Y + 1, scale: 0.82, rotation: 8, flip: true, depth: 'mid' },
      { id: 'h2_wood_1', key: 'wood_manzanita', x: 164, y: Y + 1, scale: 0.60, rotation: -8, flip: false, depth: 'mid' },
      { id: 'h2_wood_2', key: 'wood_redmoor', x: 214, y: Y + 2, scale: 0.52, rotation: -11, flip: false, depth: 'mid' },
      { id: 'h2_rot_l', key: 'rotala_full', x: 30, y: Y, scale: 0.90, rotation: 0, flip: false, depth: 'back' },
      { id: 'h2_rot_r', key: 'rotala_mid', x: 222, y: Y, scale: 0.94, rotation: 0, flip: true, depth: 'back' },
      { id: 'h2_fern', key: 'java_fern', x: 126, y: Y + 1, scale: 0.70, rotation: -2, flip: false, depth: 'front' },
      { id: 'h2_crypt', key: 'crypt', x: 182, y: Y, scale: 0.72, rotation: 1, flip: true, depth: 'back' },
      { id: 'h2_anubias', key: 'anubias', x: 84, y: Y + 1, scale: 0.78, rotation: -1, flip: false, depth: 'front' },
      { id: 'h2_moss', key: 'moss', x: 146, y: Y + 1, scale: 0.64, rotation: 0, flip: false, depth: 'front' },
      { id: 'h2_val_r', key: 'vallisneria', x: 260, y: Y, scale: 0.64, rotation: 0, flip: true, depth: 'back' },
      { id: 'h2_float_l', key: 'floating_salvinia', x: 66, y: 16, scale: 0.86, rotation: 0, flip: false, depth: 'front' },
      { id: 'h2_float_m', key: 'floating_redroot', x: 144, y: 16, scale: 0.86, rotation: 0, flip: true, depth: 'front' },
      { id: 'h2_float_r', key: 'floating_salvinia', x: 222, y: 16, scale: 0.86, rotation: 0, flip: true, depth: 'front' },
    ],
  },
};

export function clonePresetAssets(presetId) {
  const preset = SCAPE_PRESETS[presetId];
  if (!preset) return [];
  return preset.assets.map((a) => ({ ...a }));
}
